# Generated by Django 3.2.2 on 2021-05-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_work', '0003_auto_20210511_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=199, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_work.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=199, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_work.product', verbose_name='фильм'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True, verbose_name='текст'),
        ),
    ]
